"""
Aegis Dashboard
Visualizes NIDS alerts in real-time using Streamlit.
"""
import streamlit as st
import pandas as pd
import time
import os

# Page Configuration
st.set_page_config(
    page_title="Aegis NIDS Dashboard",
    page_icon="🛡️",
    layout="wide"
)

# Dashboard Title
st.title("🛡️ Aegis Network Defense System")
st.markdown("### Real-Time Threat Intelligence Monitor")

# Path to the log file generated by main.py
LOG_FILE = "alerts.csv"

def load_data():
    """
    Reads the CSV log file and returns a Pandas DataFrame.
    """
    if os.path.exists(LOG_FILE):
        try:
            return pd.read_csv(LOG_FILE)
        except pd.errors.EmptyDataError:
            return pd.DataFrame(columns=["Timestamp", "Attacker_IP", "Target_IP", "Attack_Type", "Count"])
    # Return empty structure if file doesn't exist yet
    return pd.DataFrame(columns=["Timestamp", "Attacker_IP", "Target_IP", "Attack_Type", "Count"])

# Create a placeholder for dynamic updates
placeholder = st.empty()

# Infinite loop to simulate real-time dashboard updates
while True:
    df = load_data()
    
    with placeholder.container():
        # KPI Metrics (Key Performance Indicators)
        kpi1, kpi2, kpi3 = st.columns(3)
        
        total_attacks = len(df)
        unique_attackers = df["Attacker_IP"].nunique() if not df.empty else 0
        last_attack_time = df["Timestamp"].iloc[-1] if not df.empty else "Waiting..."

        kpi1.metric(label="Total Alerts", value=total_attacks, delta="All Time")
        kpi2.metric(label="Unique Attackers", value=unique_attackers, delta="Source IPs")
        kpi3.metric(label="Last Incident", value=last_attack_time, delta="Time")

        # Layout: Charts
        col1, col2 = st.columns([2, 1])

        with col1:
            st.subheader("🚨 Attack Frequency")
            if not df.empty:
                st.line_chart(df["Count"]) # Live Line Chart
            else:
                st.info("No attacks detected yet. System is secure.")

        with col2:
            st.subheader("🌍 Top Attackers")
            if not df.empty:
                attacker_counts = df["Attacker_IP"].value_counts()
                st.bar_chart(attacker_counts) # Bar Chart
            else:
                st.write("Waiting for data...")

        # Recent Logs Table
        st.subheader("📋 Live Attack Logs")
        st.dataframe(df.tail(10), use_container_width=True) # Show last 10 entries

    # Refresh every 2 seconds
    time.sleep(2)